---
- name: Backup NX-OS running configuration
  cisco.nxos.nxos_config:
    backup: true
    backup_options:
      dir_path: "{{ playbook_dir }}/../backups"
      filename: "{{ inventory_hostname }}.cfg"
  when: ansible_network_os == 'cisco.nxos.nxos'

- name: Backup IOS running configuration
  cisco.ios.ios_config:
    backup: true
    backup_options:
      dir_path: "{{ playbook_dir }}/../backups"
      filename: "{{ inventory_hostname }}.cfg"
  when: ansible_network_os == 'cisco.ios.ios'
